[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
survey_x = "FoZGZMWrz5ATiCDJsyakp8bxF9gZjGBWZFGpJQrLEgtY"

[programs.localnet]
survey_x = "FoZGZMWrz5ATiCDJsyakp8bxF9gZjGBWZFGpJQrLEgtY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
rpc_url = "https://api.devnet.solana.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
